WIP: Tcp Portals
ockam-network/ockam pull request #1756
Opened 2021-08-17 12:46 UTC by SanjoDeundiak

2021-08-19 09:47 UTC, SanjoDeundiak commented
Merge after #1758

2021-08-20 19:09 UTC, jared-s requested changes
Very cool! A few questions, and a concern about Workflow changes

2021-08-20 20:18 UTC, SanjoDeundiak commented on .github/workflows/rust_build_ockam_ockam_examples.yml
> +  pull_request:
@jared-s my expectation was after merging #1758 this is gone during rebase

2021-08-20 20:21 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_examples/example_projects/ports/src/bin/inlet_hub.rs
> +        // };
This is under active development, already have draft PR on top of it.

2021-08-20 20:26 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_transport_tcp/src/portal/portal_sender.rs
> +            panic!("Should be last");
Done

2021-08-20 20:26 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_transport_tcp/src/portal/portal_receiver.rs
> +            let mut buf = [0u8; 256];
Done

2021-08-23 16:01 UTC, jared-s commented on .github/workflows/rust_build_ockam_ockam_examples.yml
> +  pull_request:
Ah, thanks, I'll watch for it.

2021-08-23 16:02 UTC, jared-s approved these changes

2021-08-23 17:02 UTC, jared-s commented
Merged https://github.com/ockam-network/ockam/pull/1770

2021-08-23 17:02 UTC, closed without merging