Cargo publish metadata
ockam-network/ockam pull request #2293
Opened 2021-12-01 12:42 UTC by metaclips

## Current Behaviour

## Proposed Changes
Indicate if a crate is to be published in Cargo.toml

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [ ] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [ ] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

2021-12-06 18:49 UTC, jared-s requested changes
Looking fantastic. Just one change: not yet publishing ockam_command

2021-12-06 18:49 UTC, jared-s commented on implementations/rust/ockam/ockam_command/Cargo.toml
> +publish = true
`ockam_command` isn't ready to be published, can you set this to `false` for now please?

2021-12-06 20:45 UTC, jared-s approved these changes

2021-12-06 20:46 UTC, jared-s commented
@metaclips Anything else you want to add to this branch, or shall I merge it? I'd like to try out the scripts for today's release

2021-12-06 20:54 UTC, metaclips commented
> @metaclips Anything else you want to add to this branch, or shall I merge it? I'd like to try out the scripts for today's release

It's a go @jared-s

2021-12-08 22:48 UTC, jared-s commented
Already merged as #2314

2021-12-08 22:48 UTC, closed without merging