(WIP) chore(rust): Move ockam_vault_core crate into ockam_core
ockam-network/ockam pull request #2324
Opened 2021-12-08 00:16 UTC by totsteps

closes #2288

### Tasks

- [x] Make a new `pub mod vault;` in `ockam_core`.
- [x] Move code from `ockam_vault_core/src/*` to a new `ockam_core/src/vault/*` directory.
- [ ] Update the doc comments.
- [ ] Change uses of `ockam_vault_core::Foo` to `use ockam_core::vault::Foo` across crates.
- [ ] Delete `ockam_vault_core` crate, and any references to it (be sure to check `.github/workflows`, and to do a search for `ockam_vault_core`).

### Checks
- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

2021-12-08 13:24 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_core/src/vault/types.rs
> +cfg_if! {
@antoinevg I think it's outdated approach, should we instead use compat?
P.S. This is out of scope of this PR

2021-12-08 13:26 UTC, SanjoDeundiak requested changes
Looks great. One small issue to fix

2021-12-08 13:26 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_core/src/vault/mod.rs
> +#![deny(unsafe_code)]
I think 12 lines below should be deleted, as all of this should be already present in ockam_core/src/lib.rs

2021-12-10 02:20 UTC, mrinalwadhwa commented
@totsteps awesome, this looks close to ready for merging after a couple of quick changes.


1• rebase to latest `develop` - when you do this, most file deletions `.github/workflows` will become unnecessary since ffdc3eef56b7369efe5b45b745843e88b8f730a7 removed them a few days ago.

---
2• our commitlinter will complain about this commit message because it enforces lower case.
```
chore(rust): change uses of ockam_vault_core::Foo to use ockam_core::vault::Foo across crates
```
Changing the message to this will fix the problem:
```
chore(rust): change uses of `ockam_vault_core::Foo` to use `ockam_core::vault::Foo` across crates
```
A better commit type for all commits in this PR is `refactor:` so I suggest changing the message to:
```
refactor(rust): change uses of `ockam_vault_core::Foo` to use `ockam_core::vault::Foo` across crates
```

2021-12-10 02:51 UTC, totsteps commented
Somehow I messed up when rebasing!

Will open another PR.

2021-12-10 04:12 UTC, closed without merging