feat(rust): complete secure channel implementation, fix router bugs
ockam-network/ockam pull request #485
Opened 2020-10-08 18:39 UTC by robinbudd

2020-10-08 18:43 UTC, mikelodder7 commented on implementations/rust/build.gradle
> +      //commandLine 'cargo', 'clippy', '--all', '--', '-D', 'warnings'
Did we want to keep this commented out?

2020-10-08 18:44 UTC, mikelodder7 commented on implementations/rust/c/generate_bindings/build.rs
> +        println!("cargo:warning=Test1");
probably don't need this line anymore

2020-10-08 18:44 UTC, mikelodder7 commented on implementations/rust/c/generate_bindings/build.rs
> +        println!("cargo:warning=Test2");
Or this one.

2020-10-08 18:46 UTC, mikelodder7 requested changes
Looks good. Just some suggestions. Just rebase then I can approve.

2020-10-08 21:22 UTC, robinbudd commented on implementations/rust/build.gradle
> +      //commandLine 'cargo', 'clippy', '--all', '--', '-D', 'warnings'
not any more :)

2020-10-10 21:59 UTC, mrinalwadhwa approved these changes

2020-10-10 22:03 UTC, merged