feat(rust): implement ockam credential crate
ockam-network/ockam pull request #811
Opened 2021-02-03 20:33 UTC by mikelodder7

2021-02-03 20:54 UTC, jared-s approved these changes

2021-02-03 21:55 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/CHANGELOG.md
> +## 0.1.0
```suggestion
## 0.0.0
```

2021-02-03 21:56 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/Cargo.toml
> +version = "0.1.0"
```suggestion
version = "0.0.0"
```

2021-02-03 21:57 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/CHANGELOG.md
> +
```suggestion
## Added
```

2021-02-03 22:00 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/Cargo.toml
> +readme = "READNE.md"
```suggestion
readme = "README.md"
```

2021-02-03 22:11 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/README.md
> +ockam_credentials = "0.1.0"
```suggestion
ockam_credentials = "0.0.0"
```

2021-02-03 22:12 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/README.md
> +ockam_credentials = { version = "0.1.0", default-features = false, features = ["no-std"]  }
```suggestion
ockam_credentials = { version = "0.0.0", default-features = false, features = ["no-std"]  }
```

2021-02-03 22:14 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/src/error.rs
> +#[cfg(feature = "std")]
Change to implement `From`

2021-02-03 22:18 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/src/lib.rs
> +/*
Remove license header

2021-02-03 22:26 UTC, mikelodder7 commented on implementations/rust/ockam/ockam_credentials/src/lib.rs
> +    pub xtype: AttributeType,
```suggestion
    pub attribute_type: AttributeType,
```

2021-02-04 02:01 UTC, jared-s requested changes
For consistency with other crates, let's move the crate name to the singular form `ockam_credential`

2021-02-04 22:09 UTC, jared-s approved these changes

2021-02-04 22:34 UTC, merged